### ISSUE TITLE
Daily Reports on Groups.io as a updates to a single topic rather than a new topic

### ISSUE THREAD

**Issue by pjtcb** [markmac99/UKmon-shared#297]
Groups.io is intended as a forum for discussion.  With daily reports posted each day as a new topic they can dominate the topic listing with the consequence is that it is much harder for members to find and follow discussion threads.  Also, these daily reports become less relevant as the days pass.

Daily reports might be better posted to groups.io as new posts under single "daily report' topic which can be pinned at the top of the page.

**Comment by markmac99** [comment]
Looks possible. I did a quick test and messages with identical subjects are treated as replies to the previous message. 
I'll deploy a change tonight and see if it works over the weekend. 

Note that if you're reading the group via your email client then you'll still receive each message individually (or in the digest). This is normal for replies in groups.io. However, your email client should be able to thread the replies so that they appear as a single topic. In thunderbird this can be done by clicking the "display threads" icon, and in Outlook and Thunderbird its called Conversation view.

**Comment by markmac99** [comment]
Note from Rick Hewitt:
Any chance you could include the month and year in that subject, please? 
That'd still group the messages together a fair bit, but not end up with a thread going back too far. (I ask because, in another group elsewhere,  there's been a habit of using the same subject for a few weekly reports and announcements for years, and it makes the recent ones quite hard to find in a threaded reader once they've been read for the first time...).

I'll see if the new format works then we can adjust if needed.
